// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    Alpha: typeof import('./src/components/ColorPicker/common/Alpha.vue')['default']
    Breadcrumb: typeof import('./src/components/tools/Breadcrumb.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    DescriptionList: typeof import('./src/components/DescriptionList/DescriptionList.vue')['default']
    FastDevelopBall: typeof import('./src/components/FastDevelopBall/index.vue')['default']
    FastDevelopModal: typeof import('./src/components/FastDevelopBall/FastDevelopModal.vue')['default']
    GlobalFooter: typeof import('./src/components/GlobalFooter/index.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader/index.vue')['default']
    GlobalStyle: typeof import('./src/components/SettingDrawer/components/GlobalStyle.vue')['default']
    History: typeof import('./src/components/ColorPicker/common/History.vue')['default']
    Hue: typeof import('./src/components/ColorPicker/common/Hue.vue')['default']
    LayoutSettings: typeof import('./src/components/SettingDrawer/components/LayoutSettings.vue')['default']
    LockScreen: typeof import('./src/components/LockScreen/index.vue')['default']
    Logo: typeof import('./src/components/tools/Logo.vue')['default']
    Manual: typeof import('./src/components/SvgIcon/manual.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MultiTab: typeof import('./src/components/MultiTab/index.vue')['default']
    NavigationMode: typeof import('./src/components/SettingDrawer/components/NavigationMode.vue')['default']
    NoticeIcon: typeof import('./src/components/NoticeIcon/index.vue')['default']
    OtherSettings: typeof import('./src/components/SettingDrawer/components/OtherSettings.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    RenderSubMenu: typeof import('./src/components/Menu/RenderSubMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Saturation: typeof import('./src/components/ColorPicker/common/Saturation.vue')['default']
    SettingDrawer: typeof import('./src/components/SettingDrawer/index.vue')['default']
    SettingItem: typeof import('./src/components/SettingDrawer/components/SettingItem.vue')['default']
    SideMenu: typeof import('./src/components/Menu/SideMenu.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ThemeColor: typeof import('./src/components/SettingDrawer/components/ThemeColor.vue')['default']
    TwoStepCaptcha: typeof import('./src/components/tools/TwoStepCaptcha.vue')['default']
    UserMenu: typeof import('./src/components/tools/UserMenu/index.vue')['default']
    VColorInput: typeof import('./src/components/ColorPicker/common/VColorInput.vue')['default']
  }
}

export {}
